delivery/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

main/urls.py
from django.conf.urls import url

from main.views import (
    weekly_menu_view, home_view, registration_view, login_view, logout_view,
    account_view, change_password_view, add_item_view, remove_item_view,
    add_address_view, add_delivery_time_view
)


urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^weekly_menu/$', weekly_menu_view, name='weekly_menu'),
    url(r'^registration/$', registration_view, name='registration'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^account/$', account_view, name='account'),
    url(r'^change_password/$', change_password_view, name='change_password'),
    url(r'^add_item/$', add_item_view, name='add_item'),
    url(r'^remove_item/$', remove_item_view, name='remove_item'),
    url(r'^add_address/$', add_address_view, name='add_address'),
    url(r'^add_delivery_time/$', add_delivery_time_view, name='add_delivery_time'),
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from dishes.models import Dinner


class Client(models.Model):
    phone = models.CharField(verbose_name='Номер телефона', max_length=16,
                             unique=True)
    user = models.OneToOneField(User, verbose_name='Пользователь')


class SmsCode(models.Model):
    value = models.CharField(verbose_name='СМС код', max_length=4)
    created_at = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    client = models.ForeignKey(Client, verbose_name='Клиент')


class Basket(models.Model):
    client = models.ForeignKey(Client, null=True)
    address = models.CharField(max_length=512, null=True)
    delivery_at = models.DateTimeField(null=True)


class BasketItem(models.Model):
    basket = models.ForeignKey(Basket, related_name='items')
    dinner = models.ForeignKey(Dinner)
    quantity = models.IntegerField()


class Order(models.Model):
    client = models.ForeignKey(Client)
    address = models.CharField(max_length=512)
    delivery_at = models.DateTimeField()


class OrderItem(models.Model):
    order = models.ForeignKey(Order)
    dinner = models.ForeignKey(Dinner)
    quantity = models.IntegerField()

main/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms

from main.utils import clean_phone


class RegistrationForm(forms.Form):
    phone = forms.CharField(max_length=16)
    password = forms.CharField(max_length=255)
    sms_code = forms.CharField(max_length=4, min_length=4)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        return clean_phone(phone)


class LoginForm(forms.Form):
    phone = forms.CharField(max_length=16)
    password = forms.CharField(max_length=255)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        return clean_phone(phone)


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(max_length=255)
    new_password = forms.CharField(max_length=255)
    new_password_repeat = forms.CharField(max_length=255)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        new_password = cleaned_data.get('new_password')
        new_password_repeat = cleaned_data.get('new_password_repeat')

        if new_password != new_password_repeat:
            raise forms.ValidationError('Пароли не совпадают')

        return cleaned_data

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import date, timedelta, datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from dishes.models import DailyMenu
from main.forms import RegistrationForm, LoginForm, ChangePasswordForm
from main.models import Client, Basket, BasketItem
from main.utils import get_mon_fri_of_current_week, sms_code_is_valid


def weekly_menu_view(request):
    today = date.today()
    if today.weekday() in [5, 6]:
        mon, fri = get_mon_fri_of_current_week(today + timedelta(days=2))
    else:
        mon, fri = get_mon_fri_of_current_week(today)

    weekly_menu = DailyMenu.objects.filter(date__gte=mon, date__lte=fri)

    context = {
        'today': today,
        'monday_date': mon,
        'friday_date': fri,
        'weekly_menu': weekly_menu
    }
    return render(request, 'main/weekly_menu.html', context)


def home_view(request):
    daily_menu = DailyMenu.objects.get(date=date.today())

    dinners = daily_menu.dinners.all()

    basket_id = request.session.get('basket_id')

    if not basket_id:
        if request.user.is_authenticated:
            basket = Basket.objects.create(client=request.user.client,
                                           delivery_at=daily_menu.date)
        else:
            basket = Basket.objects.create(delivery_at=daily_menu.date)

        for dinner in dinners:
            BasketItem.objects.create(basket=basket, dinner=dinner, quantity=0)

        request.session['basket_id'] = basket.id
    else:
        basket = Basket.objects.get(id=basket_id)

    context = {
        'today': date.today(),
        'dinners': dinners,
        'basket': basket
    }

    return render(request, 'main/home.html', context)


@require_POST
def add_item_view(request):
    basket_id = request.session.get('basket_id')
    basket = Basket.objects.get(id=basket_id)

    item_to_add = request.POST.get('add_item')

    if item_to_add:
        item = basket.items.get(id=item_to_add)
        item.quantity = item.quantity + 1
        item.save()

    return redirect('home')


@require_POST
def remove_item_view(request):
    basket_id = request.session.get('basket_id')
    basket = Basket.objects.get(id=basket_id)

    item_to_remove = request.POST.get('remove_item')

    if item_to_remove:
        item = basket.items.get(id=item_to_remove)
        item.quantity = item.quantity - 1 if item.quantity > 0 else 0
        item.save()

    return redirect('home')


@require_POST
def add_address_view(request):
    basket_id = request.session.get('basket_id')
    basket = Basket.objects.get(id=basket_id)

    address = request.POST.get('address')

    if address:
        basket.address = address
        basket.save()

    return redirect('home')


@require_POST
def add_address_view(request):
    basket_id = request.session.get('basket_id')
    basket = Basket.objects.get(id=basket_id)

    address = request.POST.get('address')

    if address:
        basket.address = address
        basket.save()

    return redirect('home')


@require_POST
def add_delivery_time_view(request):
    basket_id = request.session.get('basket_id')
    basket = Basket.objects.get(id=basket_id)

    minutes = request.POST.get('minutes')
    hours = request.POST.get('hours')

    if minutes and hours:
        basket.delivery_at += timedelta(hours=int(hours), minutes=int(minutes))
        basket.save()

    return redirect('home')


@require_POST
def registration_view(request):
    form = RegistrationForm(request.POST)

    if form.is_valid():
        phone = form.cleaned_data['phone']
        password = form.cleaned_data['password']
        sms_code = form.cleaned_data['sms_code']

        if Client.objects.filter(phone=phone):
            return redirect('home')

        if not sms_code_is_valid(sms_code):
            return redirect('home')

        user = User.objects.create_user(username=phone,
                                        password=password)

        Client.objects.create(phone=phone, user=user)

        login(request, user)

    return redirect('home')


@require_POST
def login_view(request):
    form = LoginForm(request.POST)

    if form.is_valid():
        phone = form.cleaned_data['phone']
        password = form.cleaned_data['password']

        try:
            Client.objects.get(phone=phone)

            user = authenticate(request, username=phone, password=password)

            if user:
                login(request, user)

                basket = Basket.objects.get(id=request.session['basket_id'])
                basket.client = user.client
                basket.save()
        except Client.DoesNotExist:
            return redirect('home')
    else:
        redirect('home')

    return redirect('home')


def logout_view(request):
    logout(request)
    return redirect('home')


@login_required
def account_view(request):
    return render(request, 'main/account.html')


@login_required
@require_POST
def change_password_view(request):
    form = ChangePasswordForm(request.POST)

    if form.is_valid():
        old_password = form.cleaned_data['old_password']
        new_password = form.cleaned_data['new_password']

        user = authenticate(request,
                            username=request.user.username,
                            password=old_password)

        if not user:
            return redirect('account')

        user.set_password(new_password)
        user.save()

        login(request, user)

    return redirect('account')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
    <div class="hero">
        <div style="background-image:url({% static 'img/design/main.png' %})"
             class="hero__image"></div>
        <div class="layout__inner">
            <div class="hero__cont">
                <div class="hero__text">доставка <span>обедов</span></div>
            </div>
            <div class="hero__bottom">
                <div class="hero__bottom-text">СМОТРИ МЕНЮ НА СЕГОДНЯ<span></span></div>
            </div>
        </div>
    </div>
    <div class="menu">
        <div class="layout__inner">
            <div class="menu__cont">
                {% for item in basket.items.all %}
                    {% include 'main/include/menu_item.html' with dinner=item.dinner item=item %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if not user.is_authenticated %}
        <div class="order">
            <div class="form">
                <div class="form__title">ОФОРМИТЬ ЗАКАЗ</div>
                <div class="form__tab">
                    <div data-tab="tab_1" class="form__tab-item active">ВХОД
                    </div>
                    <div data-tab="tab_2" class="form__tab-item">РЕГИСТРАЦИЯ
                    </div>
                </div>
                <div data-tab="tab_1" class="form__item active">
                    <form class="form__this" action="{% url 'login' %}" method="post">
                        {% csrf_token %}
                        <div class="form__line">
                            <div data-input="Номер телефона" class="input__cont input__phone">
                                <input id="id_phone" name="phone" class="input__this input__this-phone"/>
                            </div>
                        </div>
                        <div class="form__line">
                            <div data-input="Пароль" class="input__cont">
                                <input id="id_password" name="password" type="password" class="input__this"/>
                            </div>
                        </div>
                        <div class="form__bottom">
                            <button class="button">ПРОДОЛЖИТЬ</button>
                        </div>
                    </form>
                </div>
                <div data-tab="tab_2" class="form__item">
                    <form class="form__this" action="{% url 'registration' %}" method="post">
                        {% csrf_token %}
                        <div class="form__line">
                            <div data-input="Номер телефона" class="input__cont input__phone">
                                <input id="id_phone" name="phone" type="text" class="input__this input__this-phone"/>
                            </div>
                        </div>
                        <div class="form__line form__line-sms">
                            <button class="button__sms">Выслать SMS-код</button>
                            <div class="form__sms">
                                <div class="form__sms-text">SMS-КОД:</div>
                                <div class="form__sms-right">
                                    <input id="id_sms_code" name="sms_code" class="form__sms-input"/>
{#                                    <div class="form__sms-error">Неверный или пустой код</div>#}
                                </div>
                            </div>
                        </div>
                        <div class="form__line">
                            <div data-input="Пароль" class="input__cont">
                                <input id="id_password" name="password" type="password" class="input__this"/>
                            </div>
                        </div>
                        <div class="form__bottom">
                            <button class="button">РЕГИСТРАЦИЯ</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        {% if not basket.address %}
            <div class="order">
                <div class="form">
                    <div class="form__title">ОФОРМИТЬ ЗАКАЗ</div>
                    <div class="form__desc">АДРЕС ДОСТАВКИ</div>
                    <form action="{% url 'add_address' %}" method="post" class="form__this">
                        {% csrf_token %}
                        <div class="form__line">
                            <div data-input="Ваш адрес " class="input__cont">
                                <input id="id_address" name="address" class="input__this"/>
                            </div>
                        </div>
                        <div class="form__more">Если все верно:</div>
                        <div class="form__bottom">
                            <button class="button">ПРОДОЛЖИТЬ</button>
                        </div>
                    </form>
                </div>
            </div>
        {% else %}
            <div class="order">
                <div class="form">
                    <div class="form__title">ОФОРМИТЬ ЗАКАЗ</div>
                    <div class="form__desc">УКАЗАТЬ ВРЕМЯ ДОСТАВКИ</div>
                    <form action="{% url 'add_delivery_time' %}" method="post" class="form__this">
                        {% csrf_token %}
                        <div class="form__line form__line-time">
                            <div class="form__time">
                                <input id="id_hours" name="hours" placeholder="00" class="form__time-input"/>
                            </div>
                            <div class="form__time">
                                <input id="id_minutes" name="minutes" placeholder="00" class="form__time-input"/>
                            </div>
                        </div>
                        <div class="form__bottom">
                            <button class="button">ПРОДОЛЖИТЬ</button>
                        </div>
                    </form>
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

main/templates/main/weekly_menu.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Меню на неделю
{% endblock %}

{% block content %}
    <div class="weekly">
        <div class="weekly__inner">
            <div class="weekly__title">МЕНЮ НА НЕДЕЛЮ</div>
            <div class="weekly__date">
                {{ monday_date|date:'d.m.Y' }} - {{ friday_date|date:'d.m.Y' }}
            </div>
            <div class="weekly__cont">
                {% for daily_menu in weekly_menu %}
                    <div data-day="{{ daily_menu.date|date:'l' }}" class="weekly__line">
                        <div class="weekly__box">
                            {% for dinner in daily_menu.dinners.all %}
                                <div class="weekly__item">
                                    {% include 'main/include/menu_item.html' %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}